Add FERC1 output table that combines key FERC1 subtables
catalyst-cooperative/pudl pull request #1209
Opened 2021-09-08 22:21 UTC by aesharpe

This PR contains the code needed to create a composite FERC1 output table containing the information from the FERC1 `steam`, `small_gens`, `hydro`, and `pumped_storage` tables--collectively representing all of the plants reporting to FERC.

This table may have multiple uses, but the main impetus was for mapping FERC records to EIA records via the Master Unit List and FERC-EIA mapping established in the RMI repo.

Besides combining the subtables, this PR also adds new columns (like `capacity_factor` and in one case `opex_fuel_per_mwh`) to the subtables where possible so that they may be more accurately matched to EIA records. These columns are only added to subtables when they can be calculated from existing columns. 

My main question -- and why this is a _draft_ PR vs a real PR is whether this information belongs in the `output` module or the `analysis` module. While I originally thought it fit best among the outputs, I recognize that I have added some calculated fields more akin to the analysis. I would love to know what you think is most appropriate!

2021-09-13 20:02 UTC, cmgosnell requested changes
It definitely makes sense to me to keep this table in the outputs, not in analysis.

It'd be good to have this output run in the ci tests!

2021-09-16 17:37 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +                x.net_generation_mwh / (8760 * x.capacity_mw),
Can you point me to where that helper function is?

2021-09-16 17:39 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +    # Prep steam table (merge with fbp)
hmm that's a fair point! I'll do it for now.

2021-09-16 17:43 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +        raise AssertionError(
you mean something like `pd.merge(steam, fbp, how='left', on=....)` and get rid of the assertion and if len() < stuff?

2021-09-16 17:44 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +            'record_id': 'record_id_ferc1'})
mmm ok I think it's fine to leave it as `record_id`

2021-09-16 17:45 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +            'fuel_cost': 'total_fuel_cost',
probably!!

2021-09-16 21:49 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +        raise AssertionError(
I will play around with the fbp!

2021-09-16 21:50 UTC, aesharpe commented on src/pudl/output/ferc1.py
> +                x.net_generation_mwh / (8760 * x.capacity_mw),
will just keep it as is for now b/c def annual

2021-09-16 21:51 UTC, aesharpe commented
ADD THIS OUTPUT TO CI TEST

2021-09-29 20:30 UTC, merged