Integrate `f1_cash_flow` FERC1 table
catalyst-cooperative/pudl pull request #2184
Opened 2023-01-06 17:39 UTC by cmgosnell

# PR Overview
This PR integrates the `cash_flow_ferc1` table. It was mostly pretty straightforward. A few quirks/questions:
- **What to name the $s?**: Related to #2179. I named it 🥁 ... `amount`, which I don't love.
- **What to do with the start/end balances?**: I took inspiration from @zaneselvans  to just remove the starting balance. But it might not be appropriate for this table. There is ONE `amount_type` that has a starting/ending balance. And the DBF table has net change of this same `amount_type`. I believe one of the breakout XBRL tables contain this net change.
- **Weird row_number == 0**: There are two basically all null dbf records where the row_number is 0. We could deal with this in two way: a) add a row into `dbf_to_xbrl.csv` OR b) add a `targeted_drop_duplicates_dbf`. I went with a) because it felt more straightforward.

# PR Checklist

- [ ] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

2023-01-06 18:41 UTC, cmgosnell commented on src/pudl/package_data/ferc1/dbf_to_xbrl.csv
> +f1_utltyplnt_smmry,7,1994,Common,,ferc:_common_utility_member,,
this is why the builds broke! will revert. didn't mean to do that.

2023-01-06 18:54 UTC, cmgosnell commented on src/pudl/package_data/ferc1/dbf_to_xbrl.csv
> +f1_accumdepr_prvsn,8,1994,Line 8,reported_value,other_accounts_details,True,DBF contains unstructured data with a description in the item column.
there are several scattered changes throughout this CSV: `TRUE` -> `True` and `#N/A` -> `""`

this happened bc I used the XBRL taxonomy viewer thing to do the mapping bc it is way easier/less error prone imo. But it is all in TitleCase, so I read in the csv, replaced with snake_case and saved.

2023-01-06 19:03 UTC, zaneselvans requested changes
Structurally, I think this really is a starting_balance + deltas = ending_balance table, but more complex than we've seen before. I think probably everything should end up in a single column with `starting_balance` and `ending_balance` as `value_type`s, such that if you sum up all of the non-calculated (total/net) cash flow changes, and add to starting balance, you get ending balance.

2023-01-06 19:54 UTC, cmgosnell commented on src/pudl/metadata/fields.py
> +    "amount_type": {"type": "string", "description": "Type of amount reported."},
100%!

2023-01-06 19:54 UTC, cmgosnell commented on src/pudl/transform/ferc1.py
> -    @cache_df(key="xbrl")
lol

2023-01-06 19:56 UTC, cmgosnell commented on src/pudl/package_data/ferc1/dbf_to_xbrl.csv
> +f1_accumdepr_prvsn,8,1994,Line 8,reported_value,other_accounts_details,True,DBF contains unstructured data with a description in the item column.
see my comment above (i snuck it in after you started this review about why these changes showed up

2023-01-07 00:53 UTC, zaneselvans commented on src/pudl/metadata/fields.py
> +    "amount_type": {"type": "string", "description": "Type of amount reported."},
If it's going to be super generic, I think explaining why in the description would be helpful. Make it clear that it's for a wide variety of financial accounting quantities reported in FERC 1?

2023-01-07 00:54 UTC, zaneselvans approved these changes

2023-01-09 15:31 UTC, merged