Rename `heat_rate_mmbtu_mwh -> heat_rate_mmbtu_mwh_by_unit`... again
catalyst-cooperative/pudl pull request #3029
Opened 2023-11-08 01:52 UTC by bendnorman

# PR Overview
We renamed the `heat_rate_mmbtu_mwh` column to `heat_rate_mmbtu_mwh_by_unit` but merged the changes into a branch that didn't get merged in the main feature branch `rename-core-assets`. This PR rebases the changes from https://github.com/catalyst-cooperative/pudl/pull/2917 onto `rename-core-assets`.

# PR Checklist

- [ ] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

2023-11-09 00:53 UTC, zaneselvans requested changes
The only question I have is about the alembic migrations that have been changed. Should they really all be getting changed piecemeal like this? Or should the old ones keep referring to the old column name since... old DBs will have the old column name.

Or should we just wipe the migrations out and start anew?

2023-11-09 00:53 UTC, zaneselvans commented on migrations/versions/1ceb9897fd34_add_data_maturity_to_eia923m_tables.py
What's up with there being several migration versions in here changing? Including older ones? Is this search-and-replace gone wild? It seems like the older migrations might actually need to refer to the older column name.

Alternatively, should we wipe all the migrations periodically to keep too many layers from building up? Since I don't think we actually intend for it to be possible to migrate between all database versions.

2023-11-09 21:35 UTC, bendnorman commented
I've occasionally been clobbering and recreating the migrations when branches off of `rename-core-assets` start to diverge. I figured this was ok because we'll probably clobber and recreate a revision once we merge `rename-core-assets` into `dev`.

I don't think there is a ton of value keeping all of these small revision changes. Because we're not maintaining the schema of a production database, migrations are mostly helpful on single branches when you adjusting schemas and don't want to rerun the entire ETL to test your changes.

2023-11-14 18:33 UTC, zaneselvans commented
My concern is that it seems like there's a pre-existing auto-generated migration that's being edited here to use the new column name, which seems a bit odd -- shouldn't the old migration use the old column name?

2023-11-15 20:24 UTC, bendnorman commented
Good catch! I must have been a little too trigger-happy and accidentally renamed the columns in old revision files.

I deleted `1ceb` and `3313` because they are from `dev` and couldn't be easily merged with the "base" revision on the `rename-core-assets` branch. The changes in those two revisions are captured in `9ccf`.

2023-11-15 20:32 UTC, zaneselvans approved these changes

2023-11-16 00:41 UTC, merged