Make association assets names more consistent
catalyst-cooperative/pudl pull request #3035
Opened 2023-11-10 00:57 UTC by bendnorman

# PR Overview
This PR makes association assets more consistent by alphabetizing the linked sources and making sure linked sources come before linked entity names. See #3030 for more details.

# PR Checklist

- [ ] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

2023-11-10 01:00 UTC, bendnorman commented on src/pudl/transform/eia.py
> -    _core_table_name = f"_core_{dataset}__{table_name_no_asset_type}"
I figured creating a mapping of pre-harvested assets to harvested assets was better than my janky asset naming parsing.

2023-11-10 01:01 UTC, bendnorman commented
I decided to just recreate all of the migrations again because we're I ran into some migration conflicts and we're going to recreate them before we merge `rename-core-asset` into dev anyways.

2023-11-14 19:06 UTC, zaneselvans requested changes
Only minor internal inconsistency I noticed was that now the `epacamd_eia.py` module is named differently from the reordered assets that it helps produce, and it seemed like having them named the same would be more intuitive.

2023-11-15 19:18 UTC, bendnorman commented
Looks like there are a lot of instances of `epacems_eia` being used for variables, module names, and the archive. How difficult would it be to rename the archive? I think it makes more sense to rename just the assets in this PR and do a deeper replacement of `epacems_eia` with `eia_epacems` in a separate PR. We're planning on doing this with [references to mcoe](https://github.com/catalyst-cooperative/pudl/issues/2910).

2023-11-15 20:36 UTC, zaneselvans approved these changes

2023-11-15 20:46 UTC, merged