Refactor CEMS partitions to handle year-quarter files
catalyst-cooperative/pudl pull request #3096
Opened 2023-11-29 19:43 UTC by e-belfer

*to do: add description!*

# PR Checklist

- [ ] Merge the most recent version of the branch you are merging into (probably `dev`).
- [ ] All CI checks are passing. [Run tests locally to debug failures](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#running-tests-with-tox)
- [ ] Make sure you've included good docstrings.
- [ ] For major data coverage & analysis changes, [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation)
- [ ] Include unit tests for new functions and classes.
- [ ] Defensive data quality/sanity checks in analyses & data processing functions.
- [ ] Update the [release notes](https://catalystcoop-pudl.readthedocs.io/en/latest/release_notes.html) and reference reference the PR and related issues.
- [ ] Do your own explanatory review of the PR to help the reviewer understand what's going on and identify issues preemptively.

2023-11-29 20:27 UTC, zaneselvans commented on src/pudl/workspace/datastore.py
> +    epacems: ZenodoDoi = "10.5072/zenodo.2237"
Oooh, look it's mix-and-match production+sandbox DOIs and the number is sooo smol!

2023-12-04 20:17 UTC, e-belfer commented on test/integration/epacems_test.py
> +    # Use only Idaho if multiple quarters are given
1st quarter, not Idaho

2023-12-06 19:54 UTC, e-belfer commented on src/pudl/etl/epacems_assets.py
>          if not df.empty:  # If state-year combination has data
Should be quarter-year

2023-12-06 19:54 UTC, e-belfer commented on src/pudl/etl/epacems_assets.py
> -                    pq.read_table(
"Concat a slice of each state's data" would be clearer

2023-12-06 20:09 UTC, cmgosnell commented on src/pudl/transform/epacems.py
update docs for year-quarter

2023-12-07 02:24 UTC, zaneselvans requested changes
I'm concerned about the way we're using year and quarter as independent partition variables, directly analogous to what we did with year and state (which were really independent) when there's only a single real dimension (time) that we're trying to describe. See comments.

2023-12-08 16:21 UTC, cmgosnell commented on test/integration/epacems_test.py
> +        states=states,
yes exactly. we've effectively preserved the old format of the table and thus all of the output tools

2023-12-08 17:04 UTC, cmgosnell commented on test/unit/settings_test.py
> +            _ = EpaCemsSettings(quarters=[4, 4, 2])
we're no longer testing sorting so i made it clear that it is just duplication

2023-12-08 17:23 UTC, cmgosnell commented on src/pudl/etl/__init__.py
> +                        "limit": 2,
just the cems right now takes about 41 minutes

2023-12-11 21:06 UTC, cmgosnell commented on test/unit/workspace/datastore_test.py
> +    PROD_EPACEMS_ZEN_ID = 10233186  # This is the last numeric part of doi
this has been updated via #3139

2023-12-11 21:06 UTC, cmgosnell commented on src/pudl/workspace/datastore.py
> -    http: requests.Session
I'm not sure. ella may know but this doesn't seem like a blocking issue.

2023-12-11 22:30 UTC, zaneselvans approved these changes

2023-12-11 22:30 UTC, zaneselvans commented on src/pudl/workspace/datastore.py
> -    http: requests.Session
Yeah I think it's fine.

2023-12-12 03:47 UTC, zaneselvans commented
@cmgosnell

- I materialized the EPA CEMS assets locally so I could debug the test failures and it took nearly 2 hours, even with nothing else running.
- It's not immediately clear why it took so long though. It wasn't fully saturating either my CPUs or using all the memory.
- This is a very large performance regression. I think we need to put some effort into speeding this back up, or at least understanding why it's *so* slow. You said it "only" took 40 minutes for you, right?
- The integration / output tests were easy to fix and mostly had to do with changes to the `EpaCemsSettings` class, and the new expected behavior of the output function, which won't complain if you request state/year combos that don't exist. It just won't give you back the data it doesn't have.

2023-12-12 14:21 UTC, cmgosnell commented
thanks for fixing that ci failure!

Its curious that it took you 2 hours. eeee. it has consistently taken my computer ~40 minutes. When it needed to download a new archive, it took 58. Which is still ~2x time from the previous setup. I 100% agree that we should take some time to make it faster, but I don't think we should delay integrating this before we do that.

2023-12-12 15:28 UTC, zaneselvans commented
Another weird thing that I'm seeing locally comparing my two sets of outputs is the new ETL produces significantly smaller outputs, despite including a little bit more data.

```
4.8G	epacems_quarterly/
5.7G	hourly_emissions_epacems/
```
```
5.1G	hourly_emissions_epacems.parquet
5.6G	hourly_emissions_epacems.parquet (from nightly build)
```

2023-12-12 16:25 UTC, zaneselvans commented
Hmm. Using the MacOS Activity Monitor (rather than btop) I see 10 python3.11 processes each of which claims to have 20 threads, and appears to be using multiple GB of memory, which means a lot of it is spilling onto swap on disk which would slow things down a lot.

2023-12-12 16:37 UTC, merged