Remove obsolete Docker data access instructions.
catalyst-cooperative/pudl pull request #3156
Opened 2023-12-13 23:09 UTC by zaneselvans

# Overview

* Removed obsolete references in the README to using Docker containers + Jupyter locally to access data.
* Added pointers to Kaggle and Zenodo instead.

How did you make sure this worked? How can a reviewer verify this?

```[tasklist]
# To-do list
- [x] Ran the docs build locally.
```

2023-12-14 17:57 UTC, jdangerx approved these changes

2023-12-14 18:01 UTC, cmgosnell requested changes
I'm going to be honest, at a high level I greatly dislike that this whole `How do I access the data?` does not just include a bunch of links to the data [access page](https://catalystcoop-pudl.readthedocs.io/en/latest/data_access.html). Bc these two sets of access modes often diverge and end up having conflicting information. Could we just convert this whole section to be a link the the data access docs page and a list of the links to the headers on that page? Which is perhaps out of scope for this pr.

my one probably should be in scope for this pr request is that we at least add kaggle into the data access page. which could literally be a copy paste of this language.

2023-12-15 20:17 UTC, cmgosnell approved these changes

2023-12-15 20:17 UTC, cmgosnell commented on docs/data_access.rst
> +found using this Concept DOI: https://doi.org/10.5281/zenodo.3653158
1000% nit but using the "Concept DOI" language is jargony and imo not adding anything.

2023-12-15 20:17 UTC, merged