Add direct_support keys in `core_eia860__scd_generators_energy_storage` as foreign keys to `core_eia__entity_generators`
catalyst-cooperative/pudl pull request #3699
Opened 2024-06-26 14:39 UTC by e-belfer

# Overview

Closes #3695.

What problem does this address?

What did you change?

# Testing

How did you make sure this worked? How can a reviewer verify this?

```[tasklist]
# To-do list
- [ ] If updating analyses or data processing functions: make sure to update or write data validation tests (e.g.,  `test_minmax_rows()`)
- [ ] Update the [release notes](../docs/release_notes.rst): reference the PR and related issues.
- [ ] Ensure docs build, unit & integration tests, and test coverage pass locally with `make pytest-coverage` (otherwise the merge queue may reject your PR)
- [ ] Review the PR yourself and call out any questions or issues you have
- [ ] For minor ETL changes or data additions, once `make pytest-coverage` passes, make sure you have a fresh full PUDL DB downloaded locally, materialize new/changed assets and all their downstream assets and [run relevant data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `pytest` and `--live-dbs`.
- [ ] For significant ETL, data coverage or analysis changes, once `make pytest-coverage` passes, ensure the full ETL runs locally and [run data validation tests](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/testing.html#data-validation) using `make pytest-validate` (a ~10 hour run). If you can't run this locally, run the `build-deploy-pudl` GitHub Action (or ask someone with permissions to). Then, check the logs on the `#pudl-deployments` Slack channel or `gs://builds.catalyst.coop`.
```

2024-06-26 17:02 UTC, cmgosnell requested changes
amazing!!

one probably nit about boiler entity harvesting.

and one completely non-blocking request to combine the three migrations into one. I think you could do this by `alembic downgrade head-3` -> delete these three new migrations -> `alembic revision --autogenerate -m "Add my cool new direct support FKs"` -> `alembic upgrade head`

2024-06-26 17:40 UTC, e-belfer commented on src/pudl/metadata/resources/__init__.py
> +        ],
When the `boiler_id` is null any newly added `plant_id_eia` records this won't show up in the table, so no, you're correct. I will remove this.

2024-06-26 17:53 UTC, cmgosnell submitted a review, later dismissed
ty for the bb updates!

two last requests: did you check to see if this new harvesting of plant id's grabbed completely new plants? because if so we will need to add them into the pudl id mapping process. [docs](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/existing_data_updates.html#connect-datasets)

it may also change the min/max rows of the generator-based tables!

2024-06-28 19:07 UTC, e-belfer commented
@cmgosnell I expect there might be some additional row count failures that are caused by the harvesting, but I'm unable to run them locally. I'd like to just merge them into the nightly builds and patch a fix on Monday to update any remaining row count failures.

2024-06-28 19:44 UTC, zaneselvans commented
@e-belfer I think you're done for the day/week and I need to re-run my ETL locally anyway so I can give this a try and update any row counts that are off so we have a chance at getting a good build by Monday.

2024-06-28 21:45 UTC, zaneselvans commented
### Excessively null generators

Running the full ETL locally, there were some excessively null rows in the yearly and monthly generator output tables. I'd guess because these generator IDs only showed up in the new table, and were missing from the tables that provide the majority of the generator attributes. See error messages below.

<details><summary>Monthly/Yearly Generator Output Errors</summary>

```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "out_eia__yearly_generators":

The above exception was caused by the following exception:
ValueError: Found 4 Null rows in mcoe_all_gens.

  File "/Users/zane/code/catalyst/pudl/src/pudl/analysis/mcoe.py", line 209, in mcoe_generators_asset
    return mcoe_generators(
           ^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/analysis/mcoe.py", line 704, in mcoe_generators
    ).pipe(pudl.validate.no_null_rows, df_name="mcoe_all_gens", thresh=0.9)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/generic.py", line 6231, in pipe
    return common.pipe(self, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/common.py", line 502, in pipe
    return func(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/validate.py", line 124, in no_null_rows
    raise ValueError(f"Found {null_rows.sum(axis='rows')} Null rows in {df_name}.")
```

```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "out_eia__monthly_generators":

The above exception was caused by the following exception:
ValueError: Found 4 Null rows in mcoe_all_gens.

  File "/Users/zane/code/catalyst/pudl/src/pudl/analysis/mcoe.py", line 209, in mcoe_generators_asset
    return mcoe_generators(
           ^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/analysis/mcoe.py", line 704, in mcoe_generators
    ).pipe(pudl.validate.no_null_rows, df_name="mcoe_all_gens", thresh=0.9)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/generic.py", line 6231, in pipe
    return common.pipe(self, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/common.py", line 502, in pipe
    return func(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/validate.py", line 124, in no_null_rows
    raise ValueError(f"Found {null_rows.sum(axis='rows')} Null rows in {df_name}.")
```

</details>

### Expected Row Counts

Not all tables were populated due to the above errors, but for those that were populated, there were no additional changes to the row counts beyond those already documented. The only tables left unpopulated are related to the EIA Plant Parts and the FERC-EIA record linkage.

### Unmapped Plant/Utility IDs

Generating this list now...

2024-07-04 20:21 UTC, e-belfer commented
I've mapped the IDs, but these four plants are still missing a PUDL plant ID for the subsequent output tables. Need to look into this further.

2024-07-24 21:12 UTC, aesharpe approved these changes
Looks good! all assets materialized and there are no foreign key errors.

2024-07-25 15:11 UTC, e-belfer commented
The integration test failure has to do with one generator (EIA plant ID 60321, generator ID PV1) which is reported in the 860 storage direct support columns in 2023 ER data but nowhere else in the fast ETL data, causing a completely empty row and the corresponding failure.

Problem is, that plant ID and another generator (EXIS2) do exist in our data in other years (retired 2019), and so the plant attributes (location, lat/lon coords, etc.) are carrying through in the full ETL run and not triggering the null row error. The generator itself never has data. So, consistent with the other generators dropped, I've added it to the `empty_generator_ids` list.

2024-07-25 17:01 UTC, cmgosnell approved these changes
annoying but reasonable. if totally null generators continues to be a problem it might be good to apply a fix that is less specific to particular generators. but this feels like by far the most secure way to do this so 👍🏻

2024-07-25 18:33 UTC, merged